source 'https://rubygems.org'

gem 'rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc'
gem 'tzinfo-data', platforms: [:mingw, :mswin]


group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'spring'
end