# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae2739c350f73f8cae26147dfa68f1055f85e9e836058ff6043890a090a392cee6809acaec188e8561691bb4af77541a8f9db29f7c6e1d85a2981b572370b30

test:
  secret_key_base: 9938a4cf5a7f3bdfdbcb6a949d71913daa626fe02dc689545b636da34a9ee61ab879c5aa34a49f60a6d8126748e904aaf44924c9db812d2a66723662c1c3b0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
